---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "network-metrics"

resources:
  - "telegraf-meraki-agents-01_deployment.yaml"
  - "telegraf-meraki-agents-02_deployment.yaml"
  - "telegraf-meraki-agents-03_deployment.yaml"
  - "telegraf_monitor_deployment.yaml"
  - "namespace.yaml"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: "telegraf-meraki-agents-01-conf"
    files:
      - "telegraf-meraki-agents-01.conf"
  - name: "telegraf-meraki-agents-02-conf"
    files:
      - "telegraf-meraki-agents-02.conf"
  - name: "telegraf-meraki-agents-03-conf"
    files:
      - "telegraf-meraki-agents-03.conf"